apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  namespace: default
  labels:
    name: nginxservice
    backstage.io/kubernetes-id: hakka
spec:
  ports:
    - port: 82
  selector:
    app: nginx
  type: LoadBalancer
