apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    backstage.io/kubernetes-id: hakka
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
